runall:
    @for day in d*/; do cargo run -q -p $(basename $day); done

testall:
    cargo nextest run --cargo-quiet --workspace

run day:
    cargo run -p {{ day }}

test day:
    cargo nextest run --cargo-quiet -p {{ day }}
