runall:
    @for day in d*/; do cargo run -q -p $(basename $day); done

testall:
    cargo nextest run --cargo-quiet --workspace

run day:
    @for day in {{ day }}; do cargo run -p {{ day }}; done

test day:
    @for day in {{ day }}; do cargo nextest run --cargo-quiet -p {{ day }}; done
